publish_to: none

name: flutter_html_3_19_deprecations
description: This package is a fork of flutter_html by Sub6Resources. In flutter_html_3_19_deprecations, deprecated APIs removed in Flutter v3.19 have been updated, making the package compatible with the latest Flutter versions while retaining the core functionality of the original.
version: 3.0.0-alpha.6-fix
homepage: https://github.com/vladmedov/flutter_html_3_19_deprecations

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.2.0'

dependencies:
  # Plugin for parsing html
  html: '>=0.15.0 <1.0.0'

  # Plugin for parsing css
  csslib: '>=0.17.0 <1.0.0'

  # Plugin for firstWhereOrNull extension on lists
  collection: '>=1.15.0 <2.0.0'

  # plugin to convert integers to numerals
  numerus: '>=2.0.0 <3.0.0'

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
